In [1]:
import numpy as np

In [15]:
array = np.array(
    [
        [1,  99,  99, 33],
        [2, 555, 555, 44],
        [3, 666, 666, 55],
        [4, 777, 777, 66],
        [5, 888, 888, 77],
        [6,  99,  99, 88],

    ]
)

In [16]:
array.shape

(6, 4)

In [17]:
array[2:5][2:3]

array([[  5, 888, 888,  77]])

In [18]:
array[1:-1, 1:-1]

array([[555, 555],
       [666, 666],
       [777, 777],
       [888, 888]])

In [19]:
array[-5:5, -3:3]

array([[555, 555],
       [666, 666],
       [777, 777],
       [888, 888]])

In [20]:
array[1:-1][2:-1]

array([[  4, 777, 777,  66]])

In [21]:
array[2:5,2:3]

array([[666],
       [777],
       [888]])

In [22]:
array[1:5][1:3]


array([[  3, 666, 666,  55],
       [  4, 777, 777,  66]])

In [23]:
array[1:5,1:3]

array([[555, 555],
       [666, 666],
       [777, 777],
       [888, 888]])